### ISSUE TITLE
OpenShift set up for books: dev

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-books#10]
- Dev instance
  - [x] Request the creation of the website. **Note** the responsible and the name.
  - [x] Fork and work on https://gitlab.cern.ch/invenio/template-openshift.
  - [x] Deploy current repo in the dev instance.

**Comment by zzacharo** [comment]
This is currently done. You can find documentation about how to deploy new code [here](https://digital-repositories.web.cern.ch/digital-repositories/cds/books.cern.ch/operations/).
