### ISSUE TITLE
ui: make all buttons consistent

### ISSUE THREAD

**Issue by topless** [CERNDocumentServer/cds-books#43]
Decide which style we want to follow for the shake of consistency, if you cannot spot the difference, ask @kprzerwa 

![Screenshot 2019-04-12 at 15 08 14](https://user-images.githubusercontent.com/230805/56039628-f6b12d80-5d34-11e9-9a51-e5fe6dbba10e.png)
![Screenshot 2019-04-12 at 15 09 10](https://user-images.githubusercontent.com/230805/56039631-f6b12d80-5d34-11e9-96b9-f4e07afe1d58.png)

**Comment by ntarocco** [comment]
On going in the UI/UX styling EPIC
