### ISSUE TITLE
Home Page Search Bar Filter

### ISSUE THREAD

**Issue by vlad-bm** [CERNDocumentServer/cds-books#44]
Possible additional way to use the query builder helper for the homepage:

See gif:
![Query Helper.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c6d4a98807a4b0013020f6d/125516c66e82c728ace21e0d46d9819f319bc3818ae5af46b61fbcd6395428792c07b7692ac7b62bee152c51575947f917505f42fcf98f78f4b73f758b0e19f1c32f0e2a92624cf5f2d75dad0ba821824584b3b98f48c0e03f20e68e874e2c53.gif)

**Comment by ntarocco** [comment]
Link is unfortunately dead.
