### ISSUE TITLE
[Review] Sprint 13-14

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-books#51]
## Review

* Issues: 
  * [Sprint 13](https://github.com/inveniosoftware/invenio-app-ils/issues?q=is%3Aissue+milestone%3A%22Sprint+13%22+is%3Aclosed)
  * [Sprint 14](https://github.com/inveniosoftware/invenio-app-ils/issues?q=is%3Aissue+milestone%3A%22Sprint+14%22+is%3Aclosed)
* Timeline: https://cernbox.cern.ch/index.php/s/VxFEgKhlfU1S62z

### UI

* Librarian can create a loan request for a patron from a Document
* Documents: sort by available items, most loaned
* Item status can not be changed to MISSING or similar if there is an active loan on it
* Documents: statistics on past loans and renewals
* Frontsite: patron profile page
* CERN LDAP integration
* related records for languages, editions and other
* attach Item to another Document

### Migrator kit

(not yet deployed)
* in the UI, now you can see similar/matching (95% match) series to clean mistakes in titles
* migration of records relations (languages, editions, other...)

### Q&A

1. Do we need to keep files in the records? Does it happen that the record has a file, other than thesis ?
2. Discuss links to records with hashed PIDs (`/document/ABCD-UUZ`)
3. We should clarify if only users associated with CERN(having a cern email) can loan books.
4. Number of renewals in period of time and number of requests in a period of time should be per document or per item?

**Comment by agentilb** [comment]
@kprzerwa yes, we need to be able to attach files for the standards: we attach the standard to the record. It might happen, but much more rarely, for proceedings and books

**Comment by ntarocco** [comment]
1. 1 file only per electronic item (no files on Item/Documents)
