### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-books#6]
Based on the requirements documentation prepare a test script (list of test cases) to verify that the final system delivers the agreed functionality.

**Comment by costaflavio** [comment]
The file with functional tests based on requirements (U.C.) is [here](https://cernbox.cern.ch/remote.php/webdav/__myprojects/digital-repositories/Services_Projects/CDS/Books/Functional%20tests/TestCase%20Backoffice.ods?x-access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoiZmNvc3RhIiwiZ3JvdXBzIjpbXSwiZGlzcGxheV9uYW1lIjoiRmxhdmlvIENvc3RhIChmY29zdGEpIn0.IzE6VYA7P8k9--YZnj3tWjc32OQna-1LYJ5_1nKZtQY]
