### ISSUE TITLE
Termination sheet for EDH

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-books#7]
Investigate if this service is still needed. If yes, investigate if our REST endpoint can be used or if we need a custom implementation.
The current code is in our internal repo, in:  `aleph/aleph_webinterface.py`

**Comment by ludmilamarian** [comment]
After talking with our colleagues, the service is still needed. We will need to send for a specific user_id: on-loan books, loan requests, and external library loans (in line with what we are currently sending). For more details: [RQF1138512](https://cern.service-now.com/service-portal/view-request.do?n=RQF1138512)

**Comment by ntarocco** [comment]
@zzacharo I believe this is done, can you please close it if completed?

**Comment by zzacharo** [comment]
The issue has been addressed!
