### ISSUE TITLE
Search: facets and sorting

### ISSUE THREAD

**Issue by ludmilamarian** [CERNDocumentServer/cds-books#9]
Slightly updated requirements regarding facets coming from @agentilb  and Tullio:

The list of facet should indeed include:
- medium (e-books/ hard copy) 
- type (book / preprint/…) 
- language 
- authors 
- immediate availability (books available online and or not on loan)
- year of publication
- library (for the books available in paper): so people would be able to search for books in Central Library only. 

For “topic”, can we leave it for the time being, it requires a huge cleaning on our side, is it something we could add at a later stage?

For the sorting, we see: 
- year of publication 
- title
- circulation information: which is actually popularity, and beside information of circulation we could add usage statistics of ebooks, that we can provide at a regular basis. (Note that since there will be some books without paper or electronic copies, so with no “popularity”, but I guess there is no big deal, they’ll appear at the bottom of the list. 
- relevance: this is a tricky one… here we see that the results should be sorted according the closeness between the query and title/author fields. But I guess this is something to be discussed together with the search strategy. 

To Be Discussed when time comes.

**Comment by kprzerwa** [comment]
issue reviewed and split for smaller tasks, adapted accordingly to the current data structure
