### ISSUE TITLE
Error when display a document

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-books#94]
Here: https://books-dev.web.cern.ch/backoffice/documents?q=&p=1&s=10 I search 'exploring' to retrieve a document I've created, the search result is here: https://books-dev.web.cern.ch/backoffice/documents?q=exploring&sort=mostrecent&order=asc&p=1&s=10 and when I click on the record https://books-dev.web.cern.ch/backoffice/documents/0png2-mbk12 the page is fully blank
Browser used: firefox

**Comment by agentilb** [comment]
https://books-dev.web.cern.ch/search?q=exploring&p=1&s=10
-> when I click on the document, I get this message:

UI Error
Something went wrong when rendering the component

**Comment by ntarocco** [comment]
Thank you for reporting this. The error is `this.metadata.keywords is undefined`, it looks like that the UI is not happy when there are no keyword. It is a bug.
We are going to fix this soon.

**Comment by ntarocco** [comment]
Fixed by: https://github.com/inveniosoftware/invenio-app-ils/pull/831

**Comment by ntarocco** [comment]
@agentilb the fix has been deployed and you should now be able to progress with your tests.
Be aware that we have some cache issues for the moment, you will have to hard refresh the browser the first time (if you see the new book covers from Syndetics is a good sign).
